version: '3'

services:
  backend:
    build:
      context: ./docker/backend
    volumes:
      - ${APPLICATION}:/opt/app
    ports:
      - ${BACKEND_PORT}:8080
    networks:
      - backend

  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - backend

networks:
  backend:

volumes:
  data-volume: